name: Build and deploy ASP.Net Core app to Azure Web App - qarz-daftar

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Run Unit Tests
        run: dotnet test QarzDaftar.Server/QarzDaftar.Server.Api.Tests.Unit

      - name: Build with dotnet
        run: dotnet build QarzDaftar.Server/QarzDaftar.Server.Api --configuration Release

      - name: dotnet publish
        run: dotnet publish QarzDaftar.Server/QarzDaftar.Server.Api -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'qarz-daftar'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
