name: QarzDaftar Build Pipline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  Build:
    runs-on: windows-2022
    steps:
    - name: Checking Out Code
      uses: actions/checkout@v2
    - name: Seting Up .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.412
        include-prerelease: false
    - name: Restore Packages
      run: dotnet restore QarzDaftar.Server/QarzDaftar.Server.sln
    - name: Build Project
      run: dotnet build QarzDaftar.Server/QarzDaftar.Server.sln --no-restore
    - name: Run Tests
      run: dotnet test QarzDaftar.Server/QarzDaftar.Server.sln --no-build --verbosity normal
